### ISSUE TITLE
blog.py 第248行 报self.created_at.year 没有这个year这个属性

### ISSUE THREAD

**Issue by hugoren** [dongweiming/lyanna#10]
我的环境是：
   py: 3.7.2
   mysql: 5.6
   orm: Tortoise 0.11.2
  aiomysql: 0.0.20

block.py 第248行 报self.created_at.year 没有这个year这个属性

把self.created_at.yearf替换成datetime.datetime.year, 因页面展示时候，检查了这个year属性，格式异常

把self.created_at.year 写成self.created_at.tpye.year, 数据正常入库，但展示时候，格式校验异常

请指教，谢谢

**Comment by fanjindong** [comment]
+1

**Comment by dongweiming** [comment]
这个是用的ORM的问题。我再确认下哈~

**Comment by dongweiming** [comment]
@hugoren @fanjindong 我试了下，无论3.6还是3.7的版本都可以正常创建这个字段。这是[基类里面的字段](https://github.com/dongweiming/lyanna/blob/master/models/base.py#L42)

另外是不是你用了 `pipenv install`的方式？我最近改过一次 https://github.com/dongweiming/lyanna/commit/39ac48840e13b8faed02e3196c742ae9b039c0ca

觉得是你项目代码不是最新，尤其是 [orm没用我的分支](https://github.com/dongweiming/lyanna/blob/master/requirements.txt#L23)

**Comment by fanjindong** [comment]
-e git+https://github.com/dongweiming/tortoise-orm.git@dev#egg=tortoise
基于上面的方式安装的。
另外，我确实是使用pipenv

**Comment by hugoren** [comment]
好的，谢谢，是pip install
