### ISSUE TITLE
ImportError: module 'views' has no attribute 'blog'

### ISSUE THREAD

**Issue by huangtaosdt** [dongweiming/lyanna#13]
执行python app.py启动项目时，报如下错误：
Debugged import:
- 'views' found in '/root/my_project/blog_light/lyanna/views/__init__.py'.
- 'views.blog' not found.
Original exception:
ImportError: module 'views' has no attribute 'blog'

请问这是什么原因呢？

**Comment by dongweiming** [comment]
@huangtaosdt thank you for your feedback, it has been fixed! You can pull the latest code and try again
