### ISSUE TITLE
OverflowError: Maximum recursion level reached

### ISSUE THREAD

**Issue by huangtaosdt** [dongweiming/lyanna#14]
bug：
-  后台编辑某篇“带有评论”的历史文章时，返回500错误。
ps：编辑无评论信息的文章时不会触发该错误。

-  错误信息：OverflowError: Maximum recursion level reached
![image](https://user-images.githubusercontent.com/18658178/54104658-a67c3e00-440b-11e9-938c-d774502b5680.png)

**Comment by dongweiming** [comment]
@huangtaosdt thank you for your report, it has been fixed!
