### ISSUE TITLE
@huangtaosdt thank you for your report, it has been fixed!

### ISSUE THREAD

**Issue by huangtaosdt** [dongweiming/lyanna#15]
问题依旧存在..
另补几个小bug,博主不要打我[捂脸]
- 新建文章时slug为中文导致500错误，错误内容：aiomcache.exceptions.ValidationException: invalid key: b'post:\xe9\x98\xbf\xe9\x81\x93\xe5\xa4\xab:slug'
- 点击首页’标签‘无法显示内容，去掉tags路由的缓存装饰器@cache(MC_KEY_TAGS)时才可正常显示

---------
@huangtaosdt thank you for your report, it has been fixed!

_Originally posted by @dongweiming in https://github.com/dongweiming/lyanna/issues/14#issuecomment-471427393_

**Comment by dongweiming** [comment]
@huangtaosdt 

> 1. 新建文章时slug为中文导致500错误，错误内容：aiomcache.exceptions.ValidationException: invalid key: b'post:\xe9\x98\xbf\xe9\x81\x93\xe5\xa4\xab:slug'

ref: https://github.com/dongweiming/lyanna/issues/9 https://github.com/aio-libs/aiomcache/pull/119

> 2. 点击首页’标签‘无法显示内容，去掉tags路由的缓存装饰器@cache(MC_KEY_TAGS)时才可正常显示

I don't understand. How do you reproduce it?

**Comment by dongweiming** [comment]
i think e9e0e7fae11e658ff293f1cbd3b3d552fbe4a2a1 will settle the first  issue
