### ISSUE TITLE
@huangtaosdt thank you for your report, it has been fixed!

### ISSUE THREAD

**Issue by huangtaosdt** [dongweiming/lyanna#18]
@huangtaosdt thank you for your report, it has been fixed!

_Originally posted by @dongweiming in https://github.com/dongweiming/lyanna/issues/14#issuecomment-471427393_

The error still exists, when you turn off the debug mode.

**Comment by dongweiming** [comment]
@huangtaosdt Can you take a title that describes the ?

**Comment by huangtaosdt** [comment]
> @huangtaosdt Can you take a title that describes the ?

后台编辑某篇“带有评论”的历史文章时，返回500错误 。 
错误信息：OverflowError: Maximum recursion level reached

ps：此错误debug模式下不会出现
