### ISSUE TITLE
数据库初始化成功了，但是连接不上是什么情况？感谢！

### ISSUE THREAD

**Issue by ChampionWolf** [dongweiming/lyanna#19]
![image](https://user-images.githubusercontent.com/20255706/54263441-c9ddef00-45ab-11e9-8b0a-68dc24c5b80e.png)

数据库初始化成功了，但是创建用户的时候连接不上，报错是什么情况？感谢！

**Comment by dongweiming** [comment]
@ChampionWolf please confirm memcached has been started correctly. I have added [some content for this](https://dongweiming.github.io/lyanna/#/quickstart?id=%E5%87%86%E5%A4%87%E7%8E%AF%E5%A2%83)
