### ISSUE TITLE
v2.5要做的事

### ISSUE THREAD

**Issue by dongweiming** [dongweiming/lyanna#31]
想了几个点，欢迎补充:

1. [x] 优化build后的js代码的大小
2. [x] 命令行创建用户(adduser)支持交互模式输入用户名、密码、邮箱等(原来就已经支持了)
3. [x] 觉得目前文章中的语法高亮效果不好(有些该高亮没有高亮)，寻求更好的方案
4. [x] 搜索页面搜索出来的结果还带有Markdown标签(如 ###)去掉它们
5. [x] 文章显示自带「盘古之白」
6. [x] ipython的语法高亮样式(没有好的方案)
7. [x] [标签列表页面](https://www.dongwm.com/tags)按符合标签数排序显示
8. [x] 显示文章阅读量
9. [x] 文章链接可选id/title/slug

**Comment by dongweiming** [comment]
补充:

1. 显示文章阅读量

**Comment by ldsxp** [comment]
我看文章链接用的是数字id，如果改成文章名会不会方便搜索引擎索引，https://www.dongwm.com/post/148/改成https://www.dongwm.com/post/148/我为什么不喜欢 black

**Comment by dongweiming** [comment]
@ldsxp  👍 已加入TODO LIST

**Comment by dongweiming** [comment]
作为一个可选配置，中文的标题我认为不太好，另外也会支持 slug 替代 id

**Comment by dongweiming** [comment]
完成啦~
