### ISSUE TITLE
File "uvloop/loop.pyx", line 1906, in uvloop.loop.Loop.create_connection

### ISSUE THREAD

**Issue by EverydayLearning** [dongweiming/lyanna#39]
Wrong when I requested
![image](https://user-images.githubusercontent.com/35058785/67746250-143fad80-fa61-11e9-8b46-cfdf661d3318.png)

**Comment by dongweiming** [comment]
@EverydayLearning Through the error stack, it can be determined that `memcached` is not started. i will add some error tips to new users, thanks for feedback.
