### ISSUE TITLE
Undefined names: 'user' and 'cfg'

### ISSUE THREAD

**Issue by cclauss** [dongweiming/lyanna#4]
[flake8](http://flake8.pycqa.org) testing of https://github.com/dongweiming/lyanna on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./views/j.py:61:57: F821 undefined name 'user'
    liked_comment_ids = await post.comment_ids_liked_by(user['gid'])
                                                        ^
./views/index.py:91:25: F821 undefined name 'cfg'
        return redirect(cfg.oauth_redirect_path)
                        ^
2     F821 undefined name 'cfg'
2
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by dongweiming** [comment]
@cclauss Thank you for your comments, i have fixed it
