### ISSUE TITLE
win10 subsystem can't docker-compose up

### ISSUE THREAD

**Issue by yihong0618** [dongweiming/lyanna#40]
Hi~
I'm using win10 subsystem---ubuntu, when I try to docker-compose up, the web can't start.
It seems that the "the command sh -c" can not find the path, could you help me?
![image](https://user-images.githubusercontent.com/15976103/68349170-28596e00-0137-11ea-9363-1cff17b18546.png)

Then I try to docker-compose using my macbook, there's no problem/

**Comment by dongweiming** [comment]
@yihong0618 youou can pull the latest code and try again, thanks for your feedback

**Comment by dongweiming** [comment]
@yihong0618 hi, i'm not using windows system, i'm sorry to have misled you, maybe you put the lyanna code outside of `C:\Users`? 

I found some windows related issues that may be helpful to you:

https://github.com/docker/compose/issues/4303
https://github.com/docker/compose/issues/2247
https://github.com/docker/compose/issues/2548

**Comment by yihong0618** [comment]
Still have the same problem, seems that it is not a good idea for docker-compose in win10-ubuntu. I decide to do it with my mac, Really thanks a lot~~
