### ISSUE TITLE
启用config.yaml报错

### ISSUE THREAD

**Issue by guvmao** [dongweiming/lyanna#42]
我 cp config.yaml.tmpl config.yaml ,之后去首页就是如下的情况
![image](https://user-images.githubusercontent.com/40655731/69865740-076edd80-12dd-11ea-8f62-fb69e09d4cb3.png)

**Comment by guvmao** [comment]
请忽略以前的问题,这个新的问题我该如何处理呢,因为我是对python不了解的,所以希望能够指教一下.

**Comment by dongweiming** [comment]
@guvmao Sanic框架的报错堆栈体验不好，这个时候得看终端输出了什么

**Comment by dongweiming** [comment]
https://github.com/dongweiming/lyanna/commit/bd0fe4f5f666060c7e412c511e387b59d6d55c86 这个应该有帮助，你可以拉最新的代码再试~ 感谢反馈

**Comment by guvmao** [comment]
非常抱歉,我依然不明白,我希望得到的帮助是 我直接进行CP的操作,可以正常如您的博客一样可以看到侧边栏,然后我再对相关内容进行替换,但是现在显然不是这个样子.

**Comment by dongweiming** [comment]
建议你学习一些Python和博客知识再来
