### ISSUE TITLE
你这要是英文文档，星星数量估计要乘以10

### ISSUE THREAD

**Issue by sunshineinwater** [dongweiming/lyanna#45]
如题。
附赞👍

**Comment by dongweiming** [comment]
感谢谬赞啦~

**Comment by sunshineinwater** [comment]
真实估计。学习您的代码中..

**Comment by sunshineinwater** [comment]
顺便问一句，现在这个版本似乎没有用到sanic_auth,  而使用sanic_jwt 取代了。啥原因呢

**Comment by dongweiming** [comment]
这是实现登录功能的2种用法，sanic_auth我认为更合适传统的页面提交，sanic_jwt合适一个前后端分离项目，或者说局部提交

**Comment by abersheeran** [comment]
其实开源项目，大部分情况下都是原始作者进行维护……所谓的社区，只有很少的项目能有。就没必要那么追求 star 了。

**Comment by sunshineinwater** [comment]
已经抛弃sanic，改用fatsapi了。。。开发效率提升3倍以上。。你值得拥有

**Comment by abersheeran** [comment]
@sunshineinwater 我用 index.py。https://github.com/abersheeran/index.py 比 FastAPI 更快，开发效率也更高。

**Comment by sunshineinwater** [comment]
> @sunshineinwater 我用 index.py。https://github.com/abersheeran/index.py 比 FastAPI 更快，开发效率也更高。

看起来不错，就是还没形成生态，就怕太监了。。。

**Comment by abersheeran** [comment]
@sunshineinwater 有人用，才会有生态啊……而且都是标准 ASGI，能在 FastAPI/starlette 上跑的，index.py 也一样。

**Comment by sunshineinwater** [comment]
> @sunshineinwater 有人用，才会有生态啊……而且都是标准 ASGI，能在 FastAPI/starlette 上跑的，index.py 也一样。

等个人的先用。。。我这个是企业开发，用起来风险太大了
