### ISSUE TITLE
cache method of BaseModel raised Exception when database table altered

### ISSUE THREAD

**Issue by waketzheng** [dongweiming/lyanna#47]
1. 当修改数据库表结构之后，重新通过ModelClass.cache(pk)去获取缓存，会报错。
2. 修改数据库表结构的话，挺麻烦的，有没有像Django的migrations那样可以很方便地管理数据库的？

**Comment by dongweiming** [comment]
你说的问题1，我的方法是在改了表结构我会把Memcached杀掉重启一下(让缓存失效)

现在asyncio生态下的ORM里里面没有一个成熟稳定的migration方案，之前一直关注 https://github.com/encode/orm 它烂尾了

**Comment by waketzheng** [comment]
在tortoise-orm的issue中，找到一个migration的解决方案（没试过，不知道是否可行，但该库的作者说看着还可以的样子）：
https://github.com/tortoise/tortoise-orm/issues/8#issuecomment-575982472
