### ISSUE TITLE
是否应该用poetry替代pipenv？

### ISSUE THREAD

**Issue by waketzheng** [dongweiming/lyanna#49]
https://github.com/python-poetry/poetry

http://greyli.com/poetry-a-better-choice-than-pipenv/

**Comment by EscapeLife** [comment]
@waketzheng 个人理解，如果你正常使用 `pipenv` 的话，并没有感觉到痛点的话，没有必要非要是用 `poetry`。如果你使用中遇到了你认为的痛点，`pipenv` 没有解决，而 `poetry` 解决，你可以换。

**Comment by dongweiming** [comment]
@waketzheng 可以替换。不过我日常就是用标准库的venv(或者Python 2的virtualenv)
