### ISSUE TITLE
在当前最新代码master分支下，用Dockerfile build镜像时，安装ujson会出错

### ISSUE THREAD

**Issue by ziziran97** [dongweiming/lyanna#53]
如题，信息如下：
.
.
.

Building wheel for ujson (PEP 517): started
  Building wheel for ujson (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpy2j48o4_
       cwd: /tmp/pip-install-5xue8un9/ujson
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/deps
  creating build/temp.linux-x86_64-3.8/deps/double-conversion
  creating build/temp.linux-x86_64-3.8/deps/double-conversion/double-conversion
  creating build/temp.linux-x86_64-3.8/lib
  creating build/temp.linux-x86_64-3.8/python
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I./python -I./lib -I./deps/double-conversion/double-conversion -I/usr/local/include/python3.8 -c ./deps/double-conversion/double-conversion/strtod.cc -o build/temp.linux-x86_64-3.8/./deps/double-conversion/double-conversion/strtod.o -D_GNU_SOURCE
  gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
       ----------------------------------------
  ERROR: Failed building wheel for ujson
.
.
.
Successfully built cython asyncblink cssmin PyYAML sanic-sentry tortoise-orm lxml websockets requests-async uvloop multidict httptools yarl hiredis blinker pypika ciso8601 httpcore MarkupSafe cryptography
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly
The command '/bin/sh -c pip install -i https://pypi.tuna.tsinghua.edu.cn/simple     --trusted-host pypi.tuna.tsinghua.edu.cn -r /requirements.txt     && mkdir -p /install/lib/python3.8/site-packages     && cp -rp /usr/local/lib/python3.8/site-packages /install/lib/python3.8' returned a non-zero code: 1

**Comment by baby5** [comment]
gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
拿这个去搜下
