### ISSUE TITLE
我启动之后，打开页面只有一个my blog

### ISSUE THREAD

**Issue by bowuL** [dongweiming/lyanna#61]
RT，是还有什么操作不够吗

**Comment by dongweiming** [comment]
@bowuL 是的。首先需要创建一个管理员账号:

```bash
python manage.py adduser --name YOUR_NAME --password YOUR_PASS --email YOUR_EMAIL
```

然后使用这个管理员用户账号密码登陆管理后台(/admin)，接着就可以添加新文章、用户等内容。具体的可以先看看[文档](https://dongweiming.github.io/lyanna/#/quickstart?id=%e7%ae%a1%e7%90%86%e5%90%8e%e5%8f%b0)

**Comment by bowuL** [comment]
sorry, 我忘了修改本地yaml配置了，之前发给你邮件没收到回复然后找了半天发现的。对了，我这边有另一个问题，就是admin的vue启动会报错，不知道是不是版本问题。
![image](https://user-images.githubusercontent.com/41602940/132294903-258dee90-ed72-4b12-85ee-b06cba8734e2.png)

**Comment by bowuL** [comment]
view/admin 293，我不知道你那边有没有问题，但是我这边会报错
![image](https://user-images.githubusercontent.com/41602940/132318635-57de2e59-a822-41ec-ae56-6bc90bc17b06.png)

**Comment by dongweiming** [comment]
@bowuL 现在没问题了吧

**Comment by luklon** [comment]
/api/topics我也这里报错，请求返回５００，和bowuL 一样原因293地方出错

**Comment by dongweiming** [comment]
@luklon 修复啦，拉最新代码试试 ref: https://github.com/dongweiming/lyanna/commit/496ef8ce5fad3d73edf94d74be995514dbaf4d1e
