### ISSUE TITLE
python manage.py initdb 初始化数据库的时候 抛出异常

### ISSUE THREAD

**Issue by LuckyTom130** [dongweiming/lyanna#62]
python manage.py initdb
Warning: Cover can be displayed after installing `ffmpeg`
An open stream object is being garbage collected; call "stream.close()" explicitly.
An open stream object is being garbage collected; call "stream.close()" explicitly.
An open stream object is being garbage collected; call "stream.close()" explicitly.
Usage: manage.py [OPTIONS]
Try 'manage.py --help' for help.

**Comment by dongweiming** [comment]
@LuckyTom130 你的Python版本是？

看起来是Python的[Bug](https://bugs.python.org/issue38529)，你可以升级Python试试
