### ISSUE TITLE
项目用的python是具体哪个版本呢

### ISSUE THREAD

**Issue by flyly0755** [dongweiming/lyanna#68]
我这边mac机器上用python3.8.5安装requirements.txt 第三方依赖库，安装tortoise-orm==0.17.6报错
[pip_install_error.log](https://github.com/dongweiming/lyanna/files/7739380/pip_install_error.log)

**Comment by dongweiming** [comment]
@flyly0755 按理说大于3.8的都可以.看你这个是通过conda安装的。我推荐不要用这种软件，而是单纯的用标准库venv之类的方式来管理

**Comment by dongweiming** [comment]
@flyly0755 按理说大于3.8的都可以.看你这个是通过conda安装的。我推荐不要用这种软件，而是单纯的用标准库venv之类的方式来管理
