### ISSUE TITLE
项目中 mixin 问题

### ISSUE THREAD

**Issue by xiaobao996** [dongweiming/lyanna#71]
```python
from tortoise.models import ModelMeta

class ContentMixin(metaclass=ModelMeta):

class CommentMixin(metaclass=ModelMeta):

class ReactMixin(metaclass=ModelMeta):
```
伟明哥，请教下，我看源码中这几个 mixin 都没继承`metaclass=ModelMeta`，如果不继承 `metaclass=ModelMeta`，会不会报错？我改成以上这种写法也没报错。

**Comment by dongweiming** [comment]
@xiaobao996 使用ModelMeta在我这里面的三个Mixin里面是没有价值的。因为:

1. 这三个Mixin是为了混入一些方法，更多的是去【组合】
2. [ModelMeta这个元类在orm里面是给Model用的](https://github.com/tortoise/tortoise-orm/blob/a987d70c9ad673dbe19adf5be19e6164f331ffba/tortoise/models.py#L647)，也就是说每个模型都已经用了它，不需要重复使用

**Comment by xiaobao996** [comment]
&nbsp; &nbsp;伟明哥，有个不情之请，是这样，我之前续费过全套课程两次，这次5月4号到期了，能不能再给我免费看一个月，现在不好找工作，被裁了一个月了，有点焦虑，想把课程里的几个项目和基础复习下，如果我找到工作了再续费，再找不到工作我就打算回老家了。哎。
***@***.***&nbsp;&nbsp;
