### ISSUE TITLE
When I commit posts , raise ValidationException('invalid key', key), I'm not good at memcached~

### ISSUE THREAD

**Issue by JUNJIEDREAM** [dongweiming/lyanna#9]
<img width="1439" alt="2019-01-22 11 47 24" src="https://user-images.githubusercontent.com/16541377/51511281-939db200-1e3b-11e9-8eb0-84d6f7f8a517.png">

**Comment by JUNJIEDREAM** [comment]
<img width="1440" alt="2019-01-22 11 47 45" src="https://user-images.githubusercontent.com/16541377/51511328-ce074f00-1e3b-11e9-9ff5-1ba7b9488961.png">

**Comment by dongweiming** [comment]
@JUNJIEDREAM memcached not support chinese bytes as a key. ref: https://github.com/aio-libs/aiomcache/blob/master/aiomcache/client.py#L42

**So slug should be in english**

**Comment by dongweiming** [comment]
It seems to be the limit of aiomcache, I have already opened a issue [about this](https://github.com/aio-libs/aiomcache/issues/118  )

**Comment by JUNJIEDREAM** [comment]
> It seems to be the limit of aiomcache, I have already opened a issue [about this](https://github.com/aio-libs/aiomcache/issues/118)

Thanks，I'm get it.
